#! /usr/bin/env python3

# Copyright 2018 Mentor Graphics Corporation.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, see
# <https://www.gnu.org/licenses/>.

"""Top-level script for all Sourcery Builder commands."""

import sys
# The source directory at the end of a build should be exactly the
# same as at the start of a build, meaning no .pyc files should be
# written.
sys.dont_write_bytecode = True

import sourcery.context
import sourcery.relcfg
sourcery.context.ScriptContext().main(
    sourcery.relcfg.ReleaseConfigPathLoader(), sys.argv[1:])
