#!/bin/sh

# Handle running a command as part of a build task.

# Copyright 2018-2021 Mentor Graphics Corporation.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, see
# <https://www.gnu.org/licenses/>.

# If anything fails in this script, other than the main command being
# run or the change of directory, something is seriously broken about
# the build (e.g. disk full) and it is reasonable to allow make to
# fail rather than reporting back an error as a problem with this
# particular task.

set -e

interp=$1
build_script=$2
top_build_dir=$3
log=$4
sockdir=$5
message=$6
dir=$7
shift 7

if [ -f "$top_build_dir/build-failed" ]; then
    # Another part of the build has failed, do nothing here.
    exit 0
fi

# Failure of individual commands is reported back to the main script;
# success isn't, only the end of a task in the absence of build
# failures.

check_status ()
{
    if [ "$1" != 0 ]; then
	touch "$top_build_dir/build-failed"
	"$interp" -s -E "$build_script" rpc-client "$sockdir" "$message"
	exit 0
    fi
}

exec >> "$log" 2>&1

echo
echo "======================================================================"
printf "Command execution starting at: "
date
printf "%s" "Command:"
for word in "$@"; do
    printf " '"
    printf "%s" "$word" | sed -e "s/'/'\\\\''/g"
    printf "'"
done
echo
echo "Directory: $dir"
echo
set +e
if [ "$dir" ]; then
    cd "$dir"
    check_status "$?"
fi
"$@" < /dev/null
status=$?
set -e
echo
printf "Command exit status $status at: "
date

check_status "$status"
